package Boundary;

import Entity.AppSport;
import Control.GestoreUtenti;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class GuiAccessoRegistrazione {
    private JPanel contentPane;
    private JButton btnAccedi;
    private JButton btnRegistrati;
    private JLabel lblBenvenuto;

    // Riferimento al Controller
    private GestoreUtenti gestoreUtenti;

    public GuiAccessoRegistrazione(GestoreUtenti gestoreUtenti) {
        this.gestoreUtenti = gestoreUtenti;

        inizializzaComponenti();

        // Listener per il bottone di Login
        btnAccedi.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                apriSchermataLogin();
            }
        });

        // Listener per il bottone di Registrazione
        btnRegistrati.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                apriSchermataRegistrazione();
            }
        });
    }

    private void apriSchermataLogin() {
        JFrame frameLogin = new JFrame("Accesso Sistema Allenamenti");
        frameLogin.setContentPane(new FormLogin(gestoreUtenti).$$$getRootComponent$$$());
        frameLogin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frameLogin.pack();
        frameLogin.setLocationRelativeTo(null); // Centra la finestra
        frameLogin.setVisible(true);

        // Chiude la finestra di benvenuto attuale
        SwingUtilities.getWindowAncestor(contentPane).dispose();
    }

    private void apriSchermataRegistrazione() {
        JFrame frameReg = new JFrame("Registrazione Sistema Allenamenti");
        frameReg.setContentPane(new FormRegistrazione(gestoreUtenti).$$$getRootComponent$$$());
        frameReg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frameReg.pack();
        frameReg.setLocationRelativeTo(null); // Centra la finestra
        frameReg.setVisible(true);

        // Chiude la finestra di benvenuto attuale
        SwingUtilities.getWindowAncestor(contentPane).dispose();
    }

    private void inizializzaComponenti() {
        contentPane = new JPanel();
        contentPane.setLayout(new BoxLayout(contentPane, BoxLayout.Y_AXIS));
        contentPane.setBorder(BorderFactory.createEmptyBorder(30, 50, 30, 50)); // Margini interni

        lblBenvenuto = new JLabel("Benvenuto! Cosa vuoi fare?");
        lblBenvenuto.setAlignmentX(Component.CENTER_ALIGNMENT);
        lblBenvenuto.setFont(new Font("Arial", Font.BOLD, 16));

        btnAccedi = new JButton("Accedi");
        btnAccedi.setAlignmentX(Component.CENTER_ALIGNMENT);
        btnAccedi.setMaximumSize(new Dimension(150, 40));

        btnRegistrati = new JButton("Registrati");
        btnRegistrati.setAlignmentX(Component.CENTER_ALIGNMENT);
        btnRegistrati.setMaximumSize(new Dimension(150, 40));

        // Aggiunta dei componenti al pannello con degli spaziatori
        contentPane.add(lblBenvenuto);
        contentPane.add(Box.createRigidArea(new Dimension(0, 25))); // Spazio verticale
        contentPane.add(btnAccedi);
        contentPane.add(Box.createRigidArea(new Dimension(0, 15))); // Spazio verticale
        contentPane.add(btnRegistrati);
    }

    public JPanel getContentPane() {
        return contentPane;
    }

    {

        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Benvenuto!");
        contentPane.add(label1, new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        btnAccedi = new JButton();
        btnAccedi.setText("Accedi");
        contentPane.add(btnAccedi, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnRegistrati = new JButton();
        btnRegistrati.setText("Registrati");
        contentPane.add(btnRegistrati, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}