package Boundary;

import Entity.Atleta;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.Map;

public class GuiConfronto extends JFrame {

    private JPanel mainPanel;
    private JLabel lblTitolo;
    private JScrollPane scrollTabella;
    private JTable tblConfronto;
    private JButton btnChiudi;

    public GuiConfronto(Atleta atleta, Map<String, Double> datiConfronto) {

        setTitle("Confronto Prestazioni - " + atleta.getNome() + " " + atleta.getCognome());
        setContentPane(mainPanel);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setSize(500, 300);
        setLocationRelativeTo(null);

        inizializzaInterfaccia(atleta, datiConfronto);

        btnChiudi.setText("Chiudi Finestra");
        btnChiudi.addActionListener(e -> this.dispose());
    }

    private void inizializzaInterfaccia(Atleta atleta, Map<String, Double> datiConfronto) {
        // Imposta il titolo personalizzato
        lblTitolo.setText("Analisi Scostamenti: " + atleta.getNome() + " " + atleta.getCognome());
        lblTitolo.setFont(new Font(lblTitolo.getFont().getName(), Font.BOLD, 16));

        // Configura le colonne della Tabella
        String[] colonne = {"Indicatore", "Valore Registrato"};
        DefaultTableModel tableModel = new DefaultTableModel(colonne, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Tabella in sola lettura
            }
        };

        // Popola la tabella ciclando dinamicamente la Mappa
        if (datiConfronto != null && !datiConfronto.isEmpty()) {
            for (Map.Entry<String, Double> entry : datiConfronto.entrySet()) {
                String valoreFormattato = String.format("%.2f %%", entry.getValue());
                tableModel.addRow(new Object[]{entry.getKey(), valoreFormattato});
            }
        } else {
            tableModel.addRow(new Object[]{"Nessun dato disponibile", "-"});
        }

        tblConfronto.setModel(tableModel);
        tblConfronto.setRowHeight(30);
    }

    {
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 1, new Insets(15, 15, 15, 15), -1, 10));

        lblTitolo = new JLabel();
        lblTitolo.setText("Label");
        mainPanel.add(lblTitolo, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));

        scrollTabella = new JScrollPane();
        mainPanel.add(scrollTabella, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));

        tblConfronto = new JTable();
        scrollTabella.setViewportView(tblConfronto);

        btnChiudi = new JButton();
        btnChiudi.setText("Button");
        mainPanel.add(btnChiudi, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 35), null, 0, false));
    }

    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}