package Boundary;

import Control.AppSport;
import Control.GestoreDashboard;
import Entity.Allenatore;
import Entity.Atleta;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.Map;

public class GuiDashboard extends JFrame {

    // --- FIELD NAMES ---
    private JPanel mainPanel;
    private JLabel lblTotAtleti;
    private JLabel lblAssegnate;
    private JLabel lblCompletate;
    private JLabel lblInCorso;
    private JComboBox<String> cmbAtleti;
    private JButton btnVisualizzaProfilo;
    private JButton btnVisualizzaEvoluzione;
    private JButton btnVisualizzaConfronto;

    private Allenatore allenatoreLoggato;
    private GestoreDashboard gestoreDashboard;

    public GuiDashboard(Allenatore allenatore) {
        this.allenatoreLoggato = allenatore;
        this.gestoreDashboard = new GestoreDashboard(new AppSport());

        setTitle("Dashboard Monitoraggio Performance");
        setContentPane(mainPanel);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setSize(700, 450);
        setLocationRelativeTo(null);

        inizializzaDati();
        gestisciEventi();
    }

    private void inizializzaDati() {
        // 1. Carica indicatori aggregati
        try {
            Map<String, Integer> indicatori = gestoreDashboard.getIndicatoriAggregati(allenatoreLoggato.getIdAllenatore());
            lblTotAtleti.setText("Atleti: " + indicatori.getOrDefault("Totale Atleti", 0));
            lblAssegnate.setText("Assegnate: " + indicatori.getOrDefault("Sessioni Assegnate", 0));
            lblCompletate.setText("Completate: " + indicatori.getOrDefault("Sessioni Completate", 0));
            lblInCorso.setText("In Corso: " + indicatori.getOrDefault("Sessioni In Corso", 0));
        } catch (Exception e) {
            lblTotAtleti.setText("Errore dati");
        }

        // 2. Popola combo box atleti
        cmbAtleti.addItem("Seleziona un atleta...");
        for (Atleta a : allenatoreLoggato.getAtletiAssociati()) {
            cmbAtleti.addItem(a.getIdAtleta() + " - " + a.getNome() + " " + a.getCognome());
        }
    }

    private void gestisciEventi() {
        // Listener per Profilo
        btnVisualizzaProfilo.setText("Visualizza Profilo");
        btnVisualizzaProfilo.addActionListener(e -> {
            Long idAtleta = getSelectedAtletaId();
            if (idAtleta != null) {
                // TODO: new GuiProfiloAtleta(idAtleta).setVisible(true);
                JOptionPane.showMessageDialog(mainPanel, "Apertura profilo atleta ID: " + idAtleta);
            }
        });

        // Listener per Evoluzione
        btnVisualizzaEvoluzione.setText("Visualizza Evoluzione");
        btnVisualizzaEvoluzione.addActionListener(e -> {
            Long idAtleta = getSelectedAtletaId();
            if (idAtleta != null) {
                try {
                    Map<Date, Integer> evoluzione = gestoreDashboard.getEvoluzioneAtleta(allenatoreLoggato.getIdAllenatore(), idAtleta);
                    JOptionPane.showMessageDialog(mainPanel, "Storico evolutivo caricato: " + evoluzione.size() + " date trovate.");
                } catch (IllegalStateException ex) {
                    JOptionPane.showMessageDialog(mainPanel, ex.getMessage(), "Attenzione", JOptionPane.WARNING_MESSAGE);
                }
            }
        });

        // Listener per Confronto
        btnVisualizzaConfronto.setText("Confronto Dati");
        btnVisualizzaConfronto.addActionListener(e -> {
            Long idAtleta = getSelectedAtletaId();
            if (idAtleta != null) {
                try {
                    Map<String, Double> confronto = gestoreDashboard.generaConfrontoPrevistoEffettivo(allenatoreLoggato.getIdAllenatore(), idAtleta);
                    String msg = "Confronto:\n" + confronto.toString();
                    JOptionPane.showMessageDialog(mainPanel, msg);
                } catch (IllegalStateException ex) {
                    JOptionPane.showMessageDialog(mainPanel, ex.getMessage(), "Attenzione", JOptionPane.WARNING_MESSAGE);
                }
            }
        });
    }

    private Long getSelectedAtletaId() {
        if (cmbAtleti.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(mainPanel, "Seleziona un atleta dalla lista.");
            return null;
        }
        String selected = (String) cmbAtleti.getSelectedItem();
        return Long.parseLong(selected.split(" - ")[0]);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 4, new Insets(0, 0, 0, 0), -1, -1));
        lblTotAtleti = new JLabel();
        lblTotAtleti.setText("Label");
        mainPanel.add(lblTotAtleti, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblAssegnate = new JLabel();
        lblAssegnate.setText("Label");
        mainPanel.add(lblAssegnate, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblCompletate = new JLabel();
        lblCompletate.setText("Label");
        mainPanel.add(lblCompletate, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblInCorso = new JLabel();
        lblInCorso.setText("Label");
        mainPanel.add(lblInCorso, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cmbAtleti = new JComboBox();
        mainPanel.add(cmbAtleti, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnVisualizzaProfilo = new JButton();
        btnVisualizzaProfilo.setText("Button");
        mainPanel.add(btnVisualizzaProfilo, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnVisualizzaEvoluzione = new JButton();
        btnVisualizzaEvoluzione.setText("Button");
        mainPanel.add(btnVisualizzaEvoluzione, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnVisualizzaConfronto = new JButton();
        btnVisualizzaConfronto.setText("Button");
        mainPanel.add(btnVisualizzaConfronto, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}