package Boundary;

import Entity.Allenatore;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class GuiHomeAllenatore extends JFrame {

    private JPanel mainPanel;
    private JLabel lblBenvenuto;
    private JButton btnGestioneSessioni;
    private JButton btnDashboard;
    private JButton btnAtletiAssociati;

    private Allenatore allenatoreLoggato;

    public GuiHomeAllenatore(Allenatore allenatore) {
        this.allenatoreLoggato = allenatore;

        //Configurazione iniziale Finestra
        setTitle("Area Personale Coach - " + allenatoreLoggato.getNome() + " " + allenatoreLoggato.getCognome());
        setContentPane(mainPanel);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(450, 350);
        setLocationRelativeTo(null);

        inizializzaDatiDellaHome();

        gestisciEventiBottoni();
    }

    private void inizializzaDatiDellaHome() {
        // Messaggio benvenuto
        lblBenvenuto.setText("Benvenuto Coach " + allenatoreLoggato.getNome() + "!");
        lblBenvenuto.setFont(new Font(lblBenvenuto.getFont().getName(), Font.BOLD, 18));

        btnGestioneSessioni.setText("Crea / Gestisci Sessioni");
        btnDashboard.setText("Dashboard");
        btnAtletiAssociati.setText("I Miei Atleti Associati");
    }

    private void gestisciEventiBottoni() {

        btnGestioneSessioni.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                GuiGestioneSessioni guiSessioni = new GuiGestioneSessioni(allenatoreLoggato);

                guiSessioni.setVisible(true);
            }
        });

        btnDashboard.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                GuiDashboard dashboard = new GuiDashboard(allenatoreLoggato);
                dashboard.setVisible(true);

            }
        });

        btnAtletiAssociati.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                try {
                    GuiAtletiAssociati guiAtleti = new GuiAtletiAssociati(allenatoreLoggato);

                    guiAtleti.setVisible(true);

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(mainPanel,
                            "Errore durante l'apertura della gestione atleti: " + ex.getMessage(),
                            "Errore",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    {
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(5, 1, new Insets(20, 20, 20, 20), -1, 15));

        lblBenvenuto = new JLabel();
        lblBenvenuto.setText("Label");
        mainPanel.add(lblBenvenuto, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));

        btnGestioneSessioni = new JButton();
        btnGestioneSessioni.setText("Button");
        mainPanel.add(btnGestioneSessioni, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 40), null, 0, false));

        btnDashboard = new JButton();
        btnDashboard.setText("Button");
        mainPanel.add(btnDashboard, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 40), null, 0, false));

        btnAtletiAssociati = new JButton();
        btnAtletiAssociati.setText("Button");
        mainPanel.add(btnAtletiAssociati, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 40), null, 0, false));

        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}