package Boundary;

import Entity.AppSport;
import Control.GestoreUtenti;
import Entity.Allenatore;
import Entity.Atleta;
import Entity.ProfiloAtleta;
import Entity.Utente;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class GuiProfiloAtleta extends JFrame {

    // --- FIELD NAMES ---
    private JPanel mainPanel;
    private JLabel lblNomeCognome;
    private JLabel lblEmail;
    private JTextField txtDisciplina;
    private JTextField txtLivello;
    private JTextArea areaObiettivi;
    private JButton btnModificaSalva;

    private Atleta atletaDaVisualizzare;
    private Utente utenteLoggato;
    private GestoreUtenti gestoreUtenti;


    public GuiProfiloAtleta(Atleta atleta, Utente chiGuarda) {
        // 1. Forza la creazione della grafica prima di fare qualsiasi altra cosa
        $$$setupUI$$$();

        // 2. Scudo protettivo (come nella Dashboard)
        if (this.mainPanel == null) {
            this.mainPanel = new JPanel(new BorderLayout());
            this.mainPanel.add(new JLabel("Errore IDE: Form non compilato.", SwingConstants.CENTER), BorderLayout.CENTER);
        }

        this.atletaDaVisualizzare = atleta;
        this.utenteLoggato = chiGuarda;
        this.gestoreUtenti = new GestoreUtenti(new AppSport());

        setTitle("Profilo Sportivo - " + atletaDaVisualizzare.getNome());
        setContentPane(mainPanel);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setSize(550, 600);
        setLocationRelativeTo(null);

        // 3. Eseguiamo i metodi solo se la grafica è stata caricata correttamente
        if (this.lblEmail != null) {
            configuraPermessiEInterfaccia();
            caricaDati();
            gestisciAzioni();
        }
    }

    private void caricaDati() {
        lblNomeCognome.setText(atletaDaVisualizzare.getNome() + " " + atletaDaVisualizzare.getCognome());
        lblEmail.setText(atletaDaVisualizzare.getEmail());

        ProfiloAtleta p = atletaDaVisualizzare.getProfilo();
        if (p != null) {
            txtDisciplina.setText(p.getDisciplinaPraticata());
            txtLivello.setText(p.getLivelloEsperienza());
            areaObiettivi.setText(p.getObiettiviSportivi());
        }
    }

    private void configuraPermessiEInterfaccia() {
        boolean isAllenatore = (utenteLoggato instanceof Allenatore);

        txtDisciplina.setEditable(isAllenatore);
        txtLivello.setEditable(isAllenatore);
        areaObiettivi.setEditable(isAllenatore);

        if (isAllenatore) {
            btnModificaSalva.setText("Salva Modifiche Profilo");
            btnModificaSalva.setVisible(true);
        } else {
            btnModificaSalva.setText("Chiudi");
        }
    }

    private void gestisciAzioni() {
        btnModificaSalva.addActionListener(e -> {
            if (utenteLoggato instanceof Allenatore) {
                try {
                    gestoreUtenti.modificaProfiloAtleta(
                            ((Allenatore) utenteLoggato).getIdAllenatore(),
                            atletaDaVisualizzare.getIdAtleta(),
                            txtDisciplina.getText(),
                            txtLivello.getText(),
                            areaObiettivi.getText()
                    );

                    ProfiloAtleta nuovoProfilo = new ProfiloAtleta(txtDisciplina.getText(), txtLivello.getText(), areaObiettivi.getText());
                    atletaDaVisualizzare.impostaProfilo(nuovoProfilo);

                    JOptionPane.showMessageDialog(mainPanel, "Profilo aggiornato con successo!");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(mainPanel, "Errore: " + ex.getMessage());
                }
            } else {
                this.dispose();
            }
        });
    }

    {
        // Rimosso il blocco statico duplicato per evitare chiamate ridondanti
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(6, 3, new Insets(15, 15, 15, 15), -1, -1));

        lblNomeCognome = new JLabel();
        lblNomeCognome.setText("Label");
        lblNomeCognome.setFont(new Font(lblNomeCognome.getFont().getName(), Font.BOLD, 16));
        mainPanel.add(lblNomeCognome, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));

        // CORREZIONE: Qui IntelliJ aveva creato "label1" invece di "lblEmail"
        lblEmail = new JLabel();
        lblEmail.setText("Label");
        mainPanel.add(lblEmail, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));

        txtDisciplina = new JTextField();
        txtDisciplina.setText("");
        mainPanel.add(txtDisciplina, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));

        txtLivello = new JTextField();
        mainPanel.add(txtLivello, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));

        btnModificaSalva = new JButton();
        btnModificaSalva.setText("Button");
        mainPanel.add(btnModificaSalva, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));

        areaObiettivi = new JTextArea();
        mainPanel.add(areaObiettivi, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));

        final JLabel label2 = new JLabel();
        label2.setText("Disciplina Praticata:");
        mainPanel.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));

        final JLabel label3 = new JLabel();
        label3.setText("Livello:");
        mainPanel.add(label3, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));

        final JLabel label4 = new JLabel();
        label4.setText("Obiettivi:");
        mainPanel.add(label4, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}